# Color theme
import = [
    "/usr/share/alacritty/themes/zenburn.toml"
]

# [colors.primary]
# background = "#303030"
# foreground = "#d8d8d8"

[font]
size = 8.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

